import Header from "@/components/sections/header";
import type { Metadata } from "next";

import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={(inter.className, "h-[calc(100vh-3.5rem)] w-full")}>
        <Header />
        {children}
      </body>
    </html>
  );
}
